[package]
name = "Research-Unix-Shell"
version = "2.0.0"
authors = ["Morales Research Corporation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
